### ISSUE TITLE
Implementacion de código #1

### ISSUE THREAD

**Issue by JuanDiegoRM** [Kyonax/app-web-ganadera#8]
- Creacion de clases en C# de acuerdo al diagrama de clases
- Creacion de base de datos por consola
- Conexion con base de datos en SQLServer

**Comment by Kyonax** [comment]
## Implementación de código completada

[**Código App Ganadería en C#**](https://github.com/Kyonax/app-web-ganadera/tree/main/src/Ganaderia.App) - Objetivo Completado.
